name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: ./go.mod

    - name: Check out code into the Go module directory
      uses: actions/checkout@v4

    - name: Install Lint
      run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.54.2

    - name: Lint
      run: make lint

    - name: Build
      run: go build -v .

    - name: Test
      run: make test
